services:
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - reservecar-network
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - reservecar-network

  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: "mySuperSecretKey"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - reservecar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000/api/reserveCar
        VITE_APP_NAME: ReserveCar
        VITE_GOOGLE_MAP_TOKEN: AIzaSyAjZWwQU560aitGsAzUA1vEMObhyHzs05A
    ports:
      - "5173:3000"
    depends_on:
      - backend
    networks:
      - reservecar-network


networks:
  reservecar-network:
    driver: bridge

volumes:
  db_data:
